### ISSUE TITLE
Erro no "Cria Contato1"

### ISSUE THREAD

**Issue by fehveiga** [ssteeltm/chatwootBrasil#1]
OUTPUT
1 item
ERROR: syntax error at or near ","

`{{$json.account }} ,  {{ $('Dados Chatwoot').item.json.telefone }},  {{ $('Dados Chatwoot').item.json.identificador }},  {{ $('Dados Chatwoot').item.json.nome_contato ``}}`

**[undefined]**,  1599999,  email@email.com,  Disparador

**Comment by arthurrferroni** [comment]
Fixed!
